### PR TITLE
impl Normalizable for NaiveDate

### PR DESCRIPTION
**Pull request by liquidscorpio**
Needed this for something I am working on. Thought might share with upstream. Still in draft and happy to make other changes + tests and update docs if you seek to merge.

Thanks!

### CODE REVIEW

**Review by sfackler — APPROVED** [review]

**Comment by sfackler** [comment]
Seems reasonable to me thanks! Should be good to go with a quick smoke test.

**Comment by liquidscorpio** [comment]
Thanks! Going to test a bit more before moving this out of draft stage for merge, hopefully, before the end of this week.

**Comment by liquidscorpio** [comment]
@sfackler Sorry for the delay here. Just wanted to wait on the stuff I had created this for to go live first before marking it as ready for review. Thanks!

**Comment by rudolphfroger** [comment]
I would be very happy if this could land in the next release of rust-postgres-range.

**Comment by liquidscorpio** [comment]
@sfackler Let me know if any further changes required.

**Comment by Milias** [comment]
Bumping this issue because I'm also in need of this feature.

**Pull request closed without merging**
