### PR TITLE
added Normalizable impl for Option<DateTime..

### PR DESCRIPTION
**Pull request by Dowwie**

### CODE REVIEW

**Comment by sfackler** [comment]
Huh, how does a null bound compare to the bound not being present? Are they equivalent?

**Comment by sfackler** [comment]
I don't understand - it doesn't look like that code is ever creating a `RangeBound` with a `None` in it.

The key question is if the Postgres server understands a present-but-null bound and if it will ever produce one of those.

**Comment by Dowwie** [comment]
@sfackler  what about the last test case above?

```
let d = "[,]";
    let r = create_range(d).unwrap();
    let lower = r.lower();
    let upper = r.upper();
    println!("lower: {:?},  upper: {:?}", lower, upper); 
```

**Comment by sfackler** [comment]
The `Ok(Range::new(None, None))`? That constructs an unbounded range, not a range bounded by null on both ends.

**Comment by Dowwie** [comment]
@sfackler  A RangeBound(None)?  Is that even a range type in postgres?   testing in psql, it returns an exception: DETAIL:  Missing left parenthesis or bracket.

Bounds are requirements in Postgres

**Comment by sfackler** [comment]
Ok so it sounds like this PR isn't needed then, right?

**Pull request closed without merging**
