### PR TITLE
Update to latest postgres

### LINKED ISSUE #5: Outdated?
Seems like this crate has been far behind the postgres crate. Any more updates?

### PR DESCRIPTION
**Pull request by dovahcrow**
Fixes #5

### CODE REVIEW

**Comment by sfackler** [comment]
Thanks! Looks like you'll also have to bump the Travis config to 1.20 from 1.10.

**Comment by dovahcrow** [comment]
It's rust 1.23 now dude!

**Comment by sfackler** [comment]
1.20 is the oldest supported version of Rust for the postgres crate, but 1.23 is fine too :)

**Comment by dovahcrow** [comment]
Oh I see

**Comment by dovahcrow** [comment]
All green now!

**Comment by sfackler** [comment]
Thanks!

**Pull request merged**
